### ISSUE TITLE
global env variables not supported

### ISSUE THREAD

**Issue by marscher** [abayer/dummy-travis-test#1]
These are not being treated as env vars, but something else.

Eg. exporting a PATH for every job (for what the global env is meant for), the variable is handled like this:

```
 $ bash /tmp/slave/workspace/pyemma-notebooks/hudson.20160326183836.805.sh
/tmp/slave/workspace/pyemma-notebooks/hudson.20160326183836.805.sh: line 13: [PATH=/home/mi/marscher/miniconda/bin:/home/mi/marscher/miniconda/envs/ci/bin/:/usr/local/bin:/usr/bin:/bin:/usr/games,: file or directory not found
```

PS: sorry for opening this issue here. The issue section in the main repo is disabled for whatever reason. Thank you!

**Comment by asfaltboy** [comment]
I'm not sure if anyone watches issues on this repo, you should probably follow the issues link [in the plugin info page](https://wiki.jenkins-ci.org/display/JENKINS/ShiningPanda+Plugin), which leads to this filter in the [Jenknins JIRA](https://issues.jenkins-ci.org/issues/?jql=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27shiningpanda-plugin%27).
